dist: trusty
language: php

php:
  - 7.3
  - 7.4

env:
  - ILLUMINATE_VERSION=8.*

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.3
      env: ILLUMINATE_VERSION=8.* COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.2
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.8.*
    - php: 7.2
      env: ILLUMINATE_VERSION=6.*
    - php: 7.2
      env: ILLUMINATE_VERSION=7.*

before_script:
  - travis_retry composer require "illuminate/contracts:${ILLUMINATE_VERSION}" --no-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    wget https://scrutinizer-ci.com/ocular.phar
    php ocular.phar code-coverage:upload --format=php-clover coverage.clover
